backend:
  name: auth0
  domain: YOUR_AUTH0_DOMAIN
  clientId: YOUR_AUTH0_CLIENT_ID
  audience: YOUR_AUTH0_AUDIENCE
  issuer: YOUR_AUTH0_ISSUER


media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
