backend:
  name: auth0
  domain: dev-0iep0wuai7auewi1.us.auth0.com
  clientId: pv5qGo4yEXrWPdkTqT1vk9GfoyxA1d
  audience: https://dev-0iep0wuai7auewi1.us.auth0.com/api/v2/
  issuer: https://dev-0iep0wuai7auewi1.us.auth0.com/

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
