backend:
  name: git-gateway
  branch: main  # Ana branch'in ismini buraya yaz (genellikle main veya master olur)

media_folder: "public/uploads"  # Yüklenen medya dosyalarının kaydedileceği yer
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
